version: '2'

volumes:
  some-data: {}

services:
  some-git:
    container_name: some-git
    image: buildpack-deps:jessie
    volumes:
      - some-data:/usr/src/myapp
    working_dir: /usr/src/myapp
    command:
      git clone https://github.com/railstutorial/sample_app_rails_4.git

  some-ruby:
    depends_on:
      - some-git
    image: ruby:2.0
    ports:
      - 3000:3000
    volumes:
      - some-data:/usr/src/myapp
    working_dir: /usr/src/myapp/sample_app_rails_4
    command:
      sh -c \
        'apt-get update &&
        apt-get install -y nodejs &&
        rm -rf /var/lib/apt/lists/* &&
        bundle install --without production &&
        cp config/database.yml.example config/database.yml &&
        rake db:migrate &&
        rake db:test:prepare &&
        rake &&
        rails server -d'
  some-nginx:
    depends_on:
      - some-ruby
    image: nginx
    ports:
      - 8080:80
    links:
      - some-ruby:app
    volumes:
      - some-data:/usr/src/myapp
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
