version: '2'

services:
  some-git:
    container_name: some-git
    image: buildpack-deps:jessie
    volumes:
      - some-data:/usr/src/myapp
    working_dir: /usr/src/myapp
    command:
      /bin/bash -c \
        'git clone https://github.com/carmelocuenca/social_app.git &&
        cd social_app &&
        cp config/database.yml.example config/database.yml'

  some-ruby:
    depends_on:
      - some-git
    build: .
    volumes:
      - some-data:/usr/src/myapp
    working_dir: /usr/src/myapp/social_app
    command:
      /bin/bash -c \
        'until [ -f config/database.yml ]; do echo "social_app repository is unavailable - waiting"; sleep 1; done &&
        bundle install --without production &&
        rake db:migrate &&
        rake db:test:prepare &&
        rake &&
        rails server'

  some-nginx:
    depends_on:
      - some-ruby
    image: nginx
    ports:
      - 8080:80
    links:
      - some-ruby:app
    volumes:
      - some-data:/usr/src/myapp
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  some-data: {}
