version: '2'

services:
  # docker run --rm -p 9999:5432 -e DB_PORT_5432_TCP=tcp://$POSTGRES:5432 \
  #   svendowideit/ambassador
  postgres-ambassador:
    image: svendowideit/ambassador
    environment:
      # ambassador's trick
      - DB_PORT_5432_TCP=tcp://$POSTGRES:5432
    expose:
      - 5432
    restart: always

  some-ruby:
    image: carmelocuenca/social-app:0.1
    volumes:
      - some-data:/usr/src/app
    links:
      - postgres-ambassador:db
    working_dir: /usr/src/app/
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - WEB_CONCURRENCY=1 # How many worker processes to run
      - RAILS_MAX_THREADS=16 # Configure to be the maximum number of threads
    restart: always
    # rake db:test:prepare &&
    # rake &&
    command:
      /bin/bash -c \
        'cp config/database.yml.postgresql config/database.yml &&
        until PGPASSWORD="$POSTGRES_PASSWORD" psql -h "db" -p 5432 -U "$POSTGRES_USER" -c "\l"; do >&2 echo "Postgres is unavailable - sleeping"; sleep 1; done &&
        rake db:setup &&
        rake db:migrate &&
        rake db:populate &&
        puma -C config/puma.rb'

  some-nginx:
    build: nginx/
    ports:
      - 8080:80
    links:
      - some-ruby:app
    volumes:
      - some-data:/usr/src/app
    restart: always

volumes:
  some-data: {} # shared repository
