version: '2'

services:
  some-git:
    container_name: some-git
    image: buildpack-deps:jessie
    volumes:
      - some-data:/usr/src/myapp
    working_dir: /usr/src/myapp
    command:
      /bin/bash -c \
        'git clone https://github.com/carmelocuenca/social_app.git &&
        cd social_app &&
        cp config/database.yml.postgresql config/database.yml'

  some-postgres:
    image: postgres
    volumes:
      - some-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always

  some-ruby:
    depends_on:
      - some-git
      - some-postgres
    build: .
    volumes:
      - some-data:/usr/src/myapp
    links:
      - some-postgres:db
    working_dir: /usr/src/myapp/social_app
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - WEB_CONCURRENCY=2 # How many worker processes to run
      - RAILS_MAX_THREADS=16 # Configure to be the maximum number of threads
    # restart: always
    command:
      /bin/bash -c \
        'until [ -f config/database.yml ]; do echo "social_app repository is unavailable - waiting"; sleep 1; done &&
        bundle install --without production &&
        rake db:setup &&
        rake db:migrate &&
        rake db:test:prepare &&
        rake &&
        rake db:populate &&
        puma -C config/puma.rb'

  some-nginx:
    depends_on:
      - some-ruby
    image: nginx
    ports:
      - 8080:80
    links:
      - some-ruby:app
    volumes:
      - some-data:/usr/src/myapp
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  some-data: {} # git repository
  some-pgdata: {} # posgres directory
