# Fichero de composición para la base de datos
# export CONSULIP=$(docker-machine ip consul-machine)
# docker-machine create -d virtualbox postgres-machine
# export POSTGRESIP=$(docker-machine ip postgres-machine)
# eval $(docker-machine env postgres-machine)
# docker-compose -f docker-compose-postgres.yml up
version: '2'

services:
  some-registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command:
      "-ip $POSTGRESIP consul://$CONSULIP:8500"

  some-postgres:
    depends_on:
      - some-registrator
    build: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - some-pgdata:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_PORT_5432_TCP_PORT=5432
    restart: always
volumes:
  some-pgdata: {} # postgres directory
