# ETCD=$(docker-machine ip ...) INITIAL_CLUSTER_TOKEN="incicial-cluster-token" \
# CLUSTER="etcd1=http://$ETCD:2380,etcd2=http://$ETCD:3380,etcd3=http://$ETCD:4380" \
# docker-compose -f docker--compose-etcd.yml up
#
# El lío, necesitamos la dicección de la máquina anfitrión
# y componer los nodos del cluster
#
version: '2'
services:
  etcd1:
    image: quay.io/coreos/etcd
    ports:
      - 4001:4001
      - 2380:2380
      - 2379:2379
    command:
      "-name etcd1
       -initial-advertise-peer-urls http://$ETCD:2380
       -listen-peer-urls http://0.0.0.0:2380
       -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
       -advertise-client-urls http://$ETCD:2379,http://$ETCD:4001
       -initial-cluster-token $INITIAL_CLUSTER_TOKEN
       -initial-cluster $CLUSTER
       -initial-cluster-state new"
  etcd2:
     image: quay.io/coreos/etcd
     ports:
       - 5001:4001
       - 3380:2380
       - 3379:2379
     command:
       "-name etcd2
        -initial-advertise-peer-urls http://$ETCD:3380
        -listen-peer-urls http://0.0.0.0:2380
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
        -advertise-client-urls http://$ETCD:3379,http://$ETCD:5001
        -initial-cluster-token $INITIAL_CLUSTER_TOKEN
        -initial-cluster $CLUSTER
        -initial-cluster-state new"
  etcd3:
    image: quay.io/coreos/etcd
    ports:
      - 6001:4001
      - 4380:2380
      - 4379:2379
    command:
      "-name etcd3
       -initial-advertise-peer-urls http://$ETCD:4380
       -listen-peer-urls http://0.0.0.0:2380
       -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
       -advertise-client-urls http://$ETCD:4379,http://$ETCD:6001
       -initial-cluster-token $INITIAL_CLUSTER_TOKEN
       -initial-cluster $CLUSTER
       -initial-cluster-state new"
  etcd-proxy:
    image: quay.io/coreos/etcd
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    ports:
      - 8080:8080
    restart: always
    command:
      "-proxy on
       -listen-client-urls http://0.0.0.0:8080
       -initial-cluster $CLUSTER"
